local o = vim.o
local g = vim.g

vim.scripencoding = 'utf-8'
o.encoding = 'utf-8'
o.fileencoding = 'utf-8'
o.autoindent = true
o.smartindent = true
o.hlsearch = true
o.showcmd = true
o.cmdheight = 1
o.scrolloff = 4
o.laststatus = 3
o.termguicolors = true
o.tabstop = 3
o.shiftwidth = 3
o.softtabstop = 3
o.scrolloff = 3
o.cursorline = true
o.title = true
o.mouse = 'a'
o.termguicolors = true
o.splitright = true
o.splitbelow = true
o.number = true
o.wildmode = "longest:full,full"
o.relativenumber = true
o.ignorecase = true
o.smartcase = true
o.backup = false
o.undofile = true
o.swapfile = false
o.clipboard = "unnamedplus"
o.highlighturl_enabled = true
--o.fillchars:append { eob = " " }

g.loaded_netrw = 1
g.loaded_netrwPlugin = 1
g.loaded_getscript = 1
g.loaded_tutor = 1
g.loaded_matchparen = 1
g.loaded_logiPat = 1
g.loaded_rrhelper = 1
g.loaded_netrwPlugin = 1
g.loaded_netrwSettings = 1
g.loaded_netrwFileHandlers = 1
